
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GE = 33;
  public static final int UMINUS = 11;
  public static final int STRCONST = 3;
  public static final int LPAREN = 9;
  public static final int PRINTLN = 17;
  public static final int MINUS = 6;
  public static final int RPAREN = 10;
  public static final int NOT = 29;
  public static final int SEMICOLON = 22;
  public static final int AND = 28;
  public static final int TYPEID = 37;
  public static final int LT = 30;
  public static final int LBRACES = 23;
  public static final int INTCONST = 2;
  public static final int RBRACES = 24;
  public static final int OR = 27;
  public static final int COMMA = 25;
  public static final int CLASS = 12;
  public static final int DIV = 8;
  public static final int PLUS = 5;
  public static final int ASSIGN = 36;
  public static final int IF = 13;
  public static final int THIS = 19;
  public static final int DOT = 26;
  public static final int LE = 32;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int NULL = 21;
  public static final int EQ = 35;
  public static final int READLN = 16;
  public static final int TIMES = 7;
  public static final int ELSE = 14;
  public static final int WHILE = 15;
  public static final int BOOLCONST = 4;
  public static final int NE = 34;
  public static final int OBJECTID = 38;
  public static final int GT = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTCONST",
  "STRCONST",
  "BOOLCONST",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "LPAREN",
  "RPAREN",
  "UMINUS",
  "CLASS",
  "IF",
  "ELSE",
  "WHILE",
  "READLN",
  "PRINTLN",
  "RETURN",
  "THIS",
  "NEW",
  "NULL",
  "SEMICOLON",
  "LBRACES",
  "RBRACES",
  "COMMA",
  "DOT",
  "OR",
  "AND",
  "NOT",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "EQ",
  "ASSIGN",
  "TYPEID",
  "OBJECTID"
  };
}

